# Generated by Django 3.1.5 on 2021-01-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.code'),
        ),
    ]
