# Generated by Django 3.1.5 on 2021-01-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vaccinationInfo',
            new_name='vaccination_info',
        ),
    ]
