# Generated by Django 3.1.5 on 2021-01-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210130_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='in_store',
            field=models.BooleanField(default=False),
        ),
    ]
